# Generated by Django 3.1.6 on 2021-02-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.CharField(max_length=255, verbose_name='Nombre de la tarea')),
                ('duracion', models.CharField(max_length=510, verbose_name='Duracion de la tarea e minutos')),
                ('tiempo_registrado', models.CharField(max_length=255, verbose_name='Tiempo en el que se realizo la tarea')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estado de a tarea ("Pendiente" o "Completada")')),
            ],
        ),
    ]
