# Generated by Django 3.1.6 on 2021-02-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripcio',
            new_name='descripcion',
        ),
    ]
